# Generated by Django 5.0.6 on 2024-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cropdata_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
